version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
     - "5432:5432"
    volumes:
     - pgdata:/var/lib/postgres/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
     - pgadmin-data:/var/lib/pgadmin

volumes:
 pgdata:
 pgadmin-data: