version: "3.7"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
     - "5000:5000"
    volumes:
      - ./:/app/
      - /app/node_modules
    restart: always
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
     - "5432:5432"